### ISSUE TITLE
 Face Detection does not work if I move to different tab in the browser 

### ISSUE THREAD

**Issue by krisalay** [lauirvin/react-use-face-detection-demo#1]
https://github.com/google/mediapipe/issues/4244

**Comment by lauirvin** [comment]
Closing this issue as it's related to [mediapipe issue #4244](https://github.com/google-ai-edge/mediapipe/issues/4244#issuecomment-1502778734). The behavior is due to standard browser resource management practices, which pause requestAnimationFrame and related processes when the tab loses focus. Unfortunately, there isn’t an ideal workaround due to browser restrictions on background processes for high-frequency tasks like face detection.

Thank you for understanding!
